theme: osuny
_merge: deep
outputs:
  page:
  - html
  section:
  - html
  - rss
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.gif'
    footer: '/assets/images/logo.gif'
pagination:
  pagerSize: 108